version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-server-FUT_CHAMP_BACKEND
    ports:
      - "8080:80" 
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db-FUT_CHAMP_BACKEND
    environment:
      MYSQL_ROOT_PASSWORD: miliga5506@@##
      MYSQL_DATABASE: FUT_CHAMP_BACKEND
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
      
    volumes:
      - db-data:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - "8081:80"
   
volumes:
  db-data:



 